import DbConnection from "./ConnectDb/connectdb.js";
import express from "express";
import RegisterUserRouter from "./RegisterUser_Api_Crud/post.js";
import bodyParser from "body-parser";
import * as dotenv from "dotenv";
import cors from "cors";
import loginUserRouter from "./LoginUser_Api_CRUD/LoginUserApi.js";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import productRouter from "./Product_API/product_api.js";
import cartProductRouter from "./CartProducts_API_CRUD/CartProduct_API.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use(helmet());
app.use(cookieParser());
DbConnection();
app.get("/",(req,res)=>(res.send("server connected")))
app.use("/", RegisterUserRouter);
app.use("/", loginUserRouter);
app.use("/", productRouter);
app.use("/", cartProductRouter);
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Port ${port} is listening`));
